name: NLP-Course
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - numpy
  - scipy
  - pandas
  - pandera
  - matplotlib
  - seaborn
  - scikit-learn
  - spacy
  - streamlit
  - streamlit-extras
  - mystmd
  - pytorch
  - nltk
  - gensim
  - bokeh
  - beautifulsoup4
  - lightning
  - tqdm
  - faiss-cpu
  # - ollama
  - sentence-transformers
  - pip
  - pip:
    - pandas[performance,output-formatting] 
    - mistralai
    - ollama
